server:
  port: 7060
  error:
    include-stacktrace: never

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-clientId}
            client-secret: ${google-clientSecret}
          facebook:
            client-id: ${facebook-clientId}
            client-secret: ${google-clientSecret}
  datasource:
    url: ${spring-db-url}
    username: ${spring-db-username}
    password: ${spring-db-password}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${smtp-username}
    password: ${smtp-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: ${jwt-secret}
  expiration: 864000000

firebase:
  apiKey: ${firebase-apiKey}
  authDomain: ${firebase-authDomain}
  projectId: ${firebase-projectId}
  storageBucket: ${firebase-storageBucket}
  messagingSenderId: ${firebase-messagingSenderId}
  appId: ${firebase-appId}
  measurementId: ${firebase-measurementId}

azure:
  activedirectory:
    tenant-id: ${azure-ad-tenantId}
    client-id: ${azure-ad-clientId}
    client-secret: ${azure-ad-clientSecret}
    user-group:
      allowed-group: group1

springfox:
  documentation:
    swagger:
      v2:
        host: localhost:7060
